// Generated by scripts/generate-project-catalog.mjs. Do not edit by hand.
import type { ResponsiveImageSources } from './projectCatalog';
export type ClientLogo = { id: number; filename: string; imageSources: ResponsiveImageSources };
export const clientLogos: ClientLogo[] = [
  {
    "id": 1,
    "filename": "01.png",
    "imageSources": {
      "width": 2172,
      "height": 724,
      "fallback": {
        "src": "/images/generated/client-logos/01-c2fc3cad45/256.png",
        "width": 256,
        "height": 85
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/01-c2fc3cad45/128.avif",
          "width": 128,
          "height": 43
        },
        {
          "src": "/images/generated/client-logos/01-c2fc3cad45/256.avif",
          "width": 256,
          "height": 85
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/01-c2fc3cad45/128.webp",
          "width": 128,
          "height": 43
        },
        {
          "src": "/images/generated/client-logos/01-c2fc3cad45/256.webp",
          "width": 256,
          "height": 85
        }
      ]
    }
  },
  {
    "id": 2,
    "filename": "02.png",
    "imageSources": {
      "width": 1254,
      "height": 1254,
      "fallback": {
        "src": "/images/generated/client-logos/02-b75fdd2a84/256.png",
        "width": 256,
        "height": 256
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/02-b75fdd2a84/128.avif",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/02-b75fdd2a84/256.avif",
          "width": 256,
          "height": 256
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/02-b75fdd2a84/128.webp",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/02-b75fdd2a84/256.webp",
          "width": 256,
          "height": 256
        }
      ]
    }
  },
  {
    "id": 3,
    "filename": "03.png",
    "imageSources": {
      "width": 1254,
      "height": 1254,
      "fallback": {
        "src": "/images/generated/client-logos/03-b68857f12d/256.png",
        "width": 256,
        "height": 256
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/03-b68857f12d/128.avif",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/03-b68857f12d/256.avif",
          "width": 256,
          "height": 256
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/03-b68857f12d/128.webp",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/03-b68857f12d/256.webp",
          "width": 256,
          "height": 256
        }
      ]
    }
  },
  {
    "id": 4,
    "filename": "04.png",
    "imageSources": {
      "width": 1254,
      "height": 1254,
      "fallback": {
        "src": "/images/generated/client-logos/04-07e0e94f91/256.png",
        "width": 256,
        "height": 256
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/04-07e0e94f91/128.avif",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/04-07e0e94f91/256.avif",
          "width": 256,
          "height": 256
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/04-07e0e94f91/128.webp",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/04-07e0e94f91/256.webp",
          "width": 256,
          "height": 256
        }
      ]
    }
  },
  {
    "id": 5,
    "filename": "05.png",
    "imageSources": {
      "width": 2172,
      "height": 724,
      "fallback": {
        "src": "/images/generated/client-logos/05-e09661d081/256.png",
        "width": 256,
        "height": 85
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/05-e09661d081/128.avif",
          "width": 128,
          "height": 43
        },
        {
          "src": "/images/generated/client-logos/05-e09661d081/256.avif",
          "width": 256,
          "height": 85
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/05-e09661d081/128.webp",
          "width": 128,
          "height": 43
        },
        {
          "src": "/images/generated/client-logos/05-e09661d081/256.webp",
          "width": 256,
          "height": 85
        }
      ]
    }
  },
  {
    "id": 6,
    "filename": "06.png",
    "imageSources": {
      "width": 1278,
      "height": 1230,
      "fallback": {
        "src": "/images/generated/client-logos/06-0ff5099632/256.png",
        "width": 256,
        "height": 246
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/06-0ff5099632/128.avif",
          "width": 128,
          "height": 123
        },
        {
          "src": "/images/generated/client-logos/06-0ff5099632/256.avif",
          "width": 256,
          "height": 246
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/06-0ff5099632/128.webp",
          "width": 128,
          "height": 123
        },
        {
          "src": "/images/generated/client-logos/06-0ff5099632/256.webp",
          "width": 256,
          "height": 246
        }
      ]
    }
  },
  {
    "id": 7,
    "filename": "07.png",
    "imageSources": {
      "width": 1254,
      "height": 1254,
      "fallback": {
        "src": "/images/generated/client-logos/07-52fcf119aa/256.png",
        "width": 256,
        "height": 256
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/07-52fcf119aa/128.avif",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/07-52fcf119aa/256.avif",
          "width": 256,
          "height": 256
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/07-52fcf119aa/128.webp",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/07-52fcf119aa/256.webp",
          "width": 256,
          "height": 256
        }
      ]
    }
  },
  {
    "id": 8,
    "filename": "08.png",
    "imageSources": {
      "width": 1254,
      "height": 1254,
      "fallback": {
        "src": "/images/generated/client-logos/08-ef318289db/256.png",
        "width": 256,
        "height": 256
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/08-ef318289db/128.avif",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/08-ef318289db/256.avif",
          "width": 256,
          "height": 256
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/08-ef318289db/128.webp",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/08-ef318289db/256.webp",
          "width": 256,
          "height": 256
        }
      ]
    }
  },
  {
    "id": 9,
    "filename": "09.png",
    "imageSources": {
      "width": 1964,
      "height": 801,
      "fallback": {
        "src": "/images/generated/client-logos/09-451b1a2cae/256.png",
        "width": 256,
        "height": 104
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/09-451b1a2cae/128.avif",
          "width": 128,
          "height": 52
        },
        {
          "src": "/images/generated/client-logos/09-451b1a2cae/256.avif",
          "width": 256,
          "height": 104
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/09-451b1a2cae/128.webp",
          "width": 128,
          "height": 52
        },
        {
          "src": "/images/generated/client-logos/09-451b1a2cae/256.webp",
          "width": 256,
          "height": 104
        }
      ]
    }
  },
  {
    "id": 10,
    "filename": "10.png",
    "imageSources": {
      "width": 1317,
      "height": 1194,
      "fallback": {
        "src": "/images/generated/client-logos/10-26df41bdfa/256.png",
        "width": 256,
        "height": 232
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/10-26df41bdfa/128.avif",
          "width": 128,
          "height": 116
        },
        {
          "src": "/images/generated/client-logos/10-26df41bdfa/256.avif",
          "width": 256,
          "height": 232
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/10-26df41bdfa/128.webp",
          "width": 128,
          "height": 116
        },
        {
          "src": "/images/generated/client-logos/10-26df41bdfa/256.webp",
          "width": 256,
          "height": 232
        }
      ]
    }
  },
  {
    "id": 11,
    "filename": "010.png",
    "imageSources": {
      "width": 1385,
      "height": 1136,
      "fallback": {
        "src": "/images/generated/client-logos/010-e812731ac2/256.png",
        "width": 256,
        "height": 210
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/010-e812731ac2/128.avif",
          "width": 128,
          "height": 105
        },
        {
          "src": "/images/generated/client-logos/010-e812731ac2/256.avif",
          "width": 256,
          "height": 210
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/010-e812731ac2/128.webp",
          "width": 128,
          "height": 105
        },
        {
          "src": "/images/generated/client-logos/010-e812731ac2/256.webp",
          "width": 256,
          "height": 210
        }
      ]
    }
  },
  {
    "id": 12,
    "filename": "011.png",
    "imageSources": {
      "width": 1175,
      "height": 1338,
      "fallback": {
        "src": "/images/generated/client-logos/011-a04a8db65c/256.png",
        "width": 256,
        "height": 292
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/011-a04a8db65c/128.avif",
          "width": 128,
          "height": 146
        },
        {
          "src": "/images/generated/client-logos/011-a04a8db65c/256.avif",
          "width": 256,
          "height": 292
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/011-a04a8db65c/128.webp",
          "width": 128,
          "height": 146
        },
        {
          "src": "/images/generated/client-logos/011-a04a8db65c/256.webp",
          "width": 256,
          "height": 292
        }
      ]
    }
  },
  {
    "id": 13,
    "filename": "012.png",
    "imageSources": {
      "width": 1543,
      "height": 1019,
      "fallback": {
        "src": "/images/generated/client-logos/012-2694dcf8f0/256.png",
        "width": 256,
        "height": 169
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/012-2694dcf8f0/128.avif",
          "width": 128,
          "height": 85
        },
        {
          "src": "/images/generated/client-logos/012-2694dcf8f0/256.avif",
          "width": 256,
          "height": 169
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/012-2694dcf8f0/128.webp",
          "width": 128,
          "height": 85
        },
        {
          "src": "/images/generated/client-logos/012-2694dcf8f0/256.webp",
          "width": 256,
          "height": 169
        }
      ]
    }
  },
  {
    "id": 14,
    "filename": "013.png",
    "imageSources": {
      "width": 1120,
      "height": 1405,
      "fallback": {
        "src": "/images/generated/client-logos/013-4dcd6b0886/256.png",
        "width": 256,
        "height": 321
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/013-4dcd6b0886/128.avif",
          "width": 128,
          "height": 161
        },
        {
          "src": "/images/generated/client-logos/013-4dcd6b0886/256.avif",
          "width": 256,
          "height": 321
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/013-4dcd6b0886/128.webp",
          "width": 128,
          "height": 161
        },
        {
          "src": "/images/generated/client-logos/013-4dcd6b0886/256.webp",
          "width": 256,
          "height": 321
        }
      ]
    }
  },
  {
    "id": 15,
    "filename": "014.png",
    "imageSources": {
      "width": 2171,
      "height": 724,
      "fallback": {
        "src": "/images/generated/client-logos/014-1afc9f0462/256.png",
        "width": 256,
        "height": 85
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/014-1afc9f0462/128.avif",
          "width": 128,
          "height": 43
        },
        {
          "src": "/images/generated/client-logos/014-1afc9f0462/256.avif",
          "width": 256,
          "height": 85
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/014-1afc9f0462/128.webp",
          "width": 128,
          "height": 43
        },
        {
          "src": "/images/generated/client-logos/014-1afc9f0462/256.webp",
          "width": 256,
          "height": 85
        }
      ]
    }
  },
  {
    "id": 16,
    "filename": "015.png",
    "imageSources": {
      "width": 1415,
      "height": 1111,
      "fallback": {
        "src": "/images/generated/client-logos/015-59dae86ae6/256.png",
        "width": 256,
        "height": 201
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/015-59dae86ae6/128.avif",
          "width": 128,
          "height": 101
        },
        {
          "src": "/images/generated/client-logos/015-59dae86ae6/256.avif",
          "width": 256,
          "height": 201
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/015-59dae86ae6/128.webp",
          "width": 128,
          "height": 101
        },
        {
          "src": "/images/generated/client-logos/015-59dae86ae6/256.webp",
          "width": 256,
          "height": 201
        }
      ]
    }
  },
  {
    "id": 17,
    "filename": "017.png",
    "imageSources": {
      "width": 1221,
      "height": 1288,
      "fallback": {
        "src": "/images/generated/client-logos/017-9443c7f448/256.png",
        "width": 256,
        "height": 270
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/017-9443c7f448/128.avif",
          "width": 128,
          "height": 135
        },
        {
          "src": "/images/generated/client-logos/017-9443c7f448/256.avif",
          "width": 256,
          "height": 270
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/017-9443c7f448/128.webp",
          "width": 128,
          "height": 135
        },
        {
          "src": "/images/generated/client-logos/017-9443c7f448/256.webp",
          "width": 256,
          "height": 270
        }
      ]
    }
  },
  {
    "id": 18,
    "filename": "018.png",
    "imageSources": {
      "width": 1774,
      "height": 887,
      "fallback": {
        "src": "/images/generated/client-logos/018-ef0939abd0/256.png",
        "width": 256,
        "height": 128
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/018-ef0939abd0/128.avif",
          "width": 128,
          "height": 64
        },
        {
          "src": "/images/generated/client-logos/018-ef0939abd0/256.avif",
          "width": 256,
          "height": 128
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/018-ef0939abd0/128.webp",
          "width": 128,
          "height": 64
        },
        {
          "src": "/images/generated/client-logos/018-ef0939abd0/256.webp",
          "width": 256,
          "height": 128
        }
      ]
    }
  },
  {
    "id": 19,
    "filename": "019.png",
    "imageSources": {
      "width": 1367,
      "height": 1151,
      "fallback": {
        "src": "/images/generated/client-logos/019-1aa1d3878e/256.png",
        "width": 256,
        "height": 216
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/019-1aa1d3878e/128.avif",
          "width": 128,
          "height": 108
        },
        {
          "src": "/images/generated/client-logos/019-1aa1d3878e/256.avif",
          "width": 256,
          "height": 216
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/019-1aa1d3878e/128.webp",
          "width": 128,
          "height": 108
        },
        {
          "src": "/images/generated/client-logos/019-1aa1d3878e/256.webp",
          "width": 256,
          "height": 216
        }
      ]
    }
  },
  {
    "id": 20,
    "filename": "020.png",
    "imageSources": {
      "width": 1254,
      "height": 1254,
      "fallback": {
        "src": "/images/generated/client-logos/020-8a4f665e68/256.png",
        "width": 256,
        "height": 256
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/020-8a4f665e68/128.avif",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/020-8a4f665e68/256.avif",
          "width": 256,
          "height": 256
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/020-8a4f665e68/128.webp",
          "width": 128,
          "height": 128
        },
        {
          "src": "/images/generated/client-logos/020-8a4f665e68/256.webp",
          "width": 256,
          "height": 256
        }
      ]
    }
  },
  {
    "id": 21,
    "filename": "021.png",
    "imageSources": {
      "width": 1536,
      "height": 1024,
      "fallback": {
        "src": "/images/generated/client-logos/021-0e54218169/256.png",
        "width": 256,
        "height": 171
      },
      "avif": [
        {
          "src": "/images/generated/client-logos/021-0e54218169/128.avif",
          "width": 128,
          "height": 85
        },
        {
          "src": "/images/generated/client-logos/021-0e54218169/256.avif",
          "width": 256,
          "height": 171
        }
      ],
      "webp": [
        {
          "src": "/images/generated/client-logos/021-0e54218169/128.webp",
          "width": 128,
          "height": 85
        },
        {
          "src": "/images/generated/client-logos/021-0e54218169/256.webp",
          "width": 256,
          "height": 171
        }
      ]
    }
  }
];
