// Generated by scripts/generate-project-catalog.mjs. Do not edit by hand.
import type { ResponsiveImageSources } from './projectCatalog';
export const heroImageSources: Record<number, ResponsiveImageSources> = {
  "1": {
    "width": 1532,
    "height": 1027,
    "fallback": {
      "src": "/images/generated/hero/1/1532.jpg",
      "width": 1532,
      "height": 1027
    },
    "avif": [
      {
        "src": "/images/generated/hero/1/768.avif",
        "width": 768,
        "height": 515
      },
      {
        "src": "/images/generated/hero/1/1440.avif",
        "width": 1440,
        "height": 965
      },
      {
        "src": "/images/generated/hero/1/1532.avif",
        "width": 1532,
        "height": 1027
      }
    ],
    "webp": [
      {
        "src": "/images/generated/hero/1/768.webp",
        "width": 768,
        "height": 515
      },
      {
        "src": "/images/generated/hero/1/1440.webp",
        "width": 1440,
        "height": 965
      },
      {
        "src": "/images/generated/hero/1/1532.webp",
        "width": 1532,
        "height": 1027
      }
    ]
  },
  "2": {
    "width": 2000,
    "height": 1125,
    "fallback": {
      "src": "/images/generated/hero/2/2000.jpg",
      "width": 2000,
      "height": 1125
    },
    "avif": [
      {
        "src": "/images/generated/hero/2/768.avif",
        "width": 768,
        "height": 432
      },
      {
        "src": "/images/generated/hero/2/1440.avif",
        "width": 1440,
        "height": 810
      },
      {
        "src": "/images/generated/hero/2/2000.avif",
        "width": 2000,
        "height": 1125
      }
    ],
    "webp": [
      {
        "src": "/images/generated/hero/2/768.webp",
        "width": 768,
        "height": 432
      },
      {
        "src": "/images/generated/hero/2/1440.webp",
        "width": 1440,
        "height": 810
      },
      {
        "src": "/images/generated/hero/2/2000.webp",
        "width": 2000,
        "height": 1125
      }
    ]
  },
  "3": {
    "width": 2000,
    "height": 1125,
    "fallback": {
      "src": "/images/generated/hero/3/2000.jpg",
      "width": 2000,
      "height": 1125
    },
    "avif": [
      {
        "src": "/images/generated/hero/3/768.avif",
        "width": 768,
        "height": 432
      },
      {
        "src": "/images/generated/hero/3/1440.avif",
        "width": 1440,
        "height": 810
      },
      {
        "src": "/images/generated/hero/3/2000.avif",
        "width": 2000,
        "height": 1125
      }
    ],
    "webp": [
      {
        "src": "/images/generated/hero/3/768.webp",
        "width": 768,
        "height": 432
      },
      {
        "src": "/images/generated/hero/3/1440.webp",
        "width": 1440,
        "height": 810
      },
      {
        "src": "/images/generated/hero/3/2000.webp",
        "width": 2000,
        "height": 1125
      }
    ]
  }
};
